version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    networks:
      - bot-network

  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bot-network

networks:
  bot-network:

volumes:
  pgdata:
