version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - bot-network

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A tasks.celery_config worker -l info
    volumes:
      - .:/home/user/app/
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A tasks.celery_config beat -l info
    volumes:
      - .:/home/user/app/
    depends_on:
      - redis

  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bot-network

networks:
  bot-network:

volumes:
  pgdata:
